---

- name: install pip
  hosts: ubuntu
  yum: 
    name:
      - epel-release
      - python-pip

- name: create dir for nginx
  file:
    path: /var/local/nginx/
    state: directory
 
- hosts: ubuntu
  roles:
    - docker-role
    - webapp-role
    - nginx-role


