---

- hosts: ubuntu
  vars:
    statuscode:
  tasks:
    - name: check connection (GET request) and collect http status code
      uri:
        url: http://localhost:8081
        return_content: yes
      register: statuscode
    - debug:
        var: statuscode.status
    - name: sleep
      shell: "sleep 5"
